---
title: '2.WGCNA'
author: "ZhangYuxi"
date: "2026-10-08"
output: html_document
---
# 1. Packages and global settings

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
options(future.globals.maxSize = 50 * 1024^3)
```


```{r packages}
library(Seurat)
library(tidyverse)
library(cowplot)
library(patchwork)
library(WGCNA)
library(hdWGCNA)
library(igraph)
library(dplyr)
library(stringr)
library(scCustomize)
library(paletteer)

theme_set(theme_cowplot())
set.seed(12345)
enableWGCNAThreads(nThreads = 10)
```

#2. wgcna pipeline

```{r}
scelist <- readRDS("/home/yyyuxi/vascular/ourdata/Tnc_vascular/sce_ann.rds")
sce <- scelist[["sceSMC"]]
sce$celltype <- sce$subcell
DimPlot(sce, group.by = "celltype", label = TRUE) +
  umap_theme() +
  NoLegend()
```


```{r, eval=FALSE}
cell_select <- c("rcVSMC", "ecmVSMC", "strVSMC", "OsVSMC")
sce <- SetupForWGCNA(sce, gene_select = "fraction",
                     fraction = 0.05, wgcna_name = "tutorial")

sce <- MetacellsByGroups(sce, group.by = c("celltype", "sample"),
                         reduction = "harmony", k = 25, max_shared = 10,
                         ident.group = "celltype") %>%
  NormalizeMetacells()

sce <- SetDatExpr(sce, group_name = cell_select,
                  group.by = "celltype", assay = "RNA", slot = "data")

sce <- TestSoftPowers(sce, networkType = "signed")

best_soft_power <- sce@misc$yuxi$wgcna_powerTable %>%
  filter(SFT.R.sq >= 0.8) %>%
  slice_min(SFT.R.sq) %>%
  pull(Power)

sce <- ConstructNetwork(sce, soft_power = best_soft_power,
                        setDatExpr = FALSE, tom_name = "hdwgcna")

sce <- ScaleData(sce, features = VariableFeatures(sce)) %>%
  ModuleEigengenes(group.by.vars = "sample") %>%
  ModuleConnectivity(group.by = "celltype", group_name = cell_select) %>%
  ResetModuleNames(new_name = "Module") %>%
  ModuleExprScore(n_genes = 25, method = "Seurat")

saveRDS(sce, file = "/home/yyyuxi/vascular/ourdata/Tnc_vascular/SMC_ann/wgcna/sce_wgcna.rds")
```

# 3. Visualization

```{r}
sce <- readRDS("/home/yyyuxi/vascular/ourdata/Tnc_vascular/SMC_ann/wgcna/sce_wgcna.rds")
sce$celltype <- factor(sce$celltype,
                       levels = c("rcVSMC", "ecmVSMC", "strVSMC", "OsVSMC"))
```


```{r}
wrap_plots(PlotSoftPowers(sce), ncol = 2)
```


```{r}
PlotDendrogram(sce, main = "hdWGCNA Dendrogram")
```


```{r}
umap_df <- GetModuleUMAP(sce) %>%
  mutate(module = str_replace(module, "Module", "M"))

mod_centers <- umap_df %>%
  group_by(module) %>%
  summarise(UMAP1 = median(UMAP1),
            UMAP2 = median(UMAP2),
            color = dplyr::first(color),
            .groups = "drop")

p <- ggplot(umap_df, aes(UMAP1, UMAP2)) +
  geom_point(color = umap_df$color, size = umap_df$kME * 2) +
  geom_label(data = mod_centers,
             aes(UMAP1, UMAP2, label = module, fill = module),
             color = "white", size = 4, fontface = "bold",
             label.padding = unit(0.2, "lines"), show.legend = FALSE) +
  scale_fill_manual(values = setNames(mod_centers$color, mod_centers$module)) +
  umap_theme() 

print(p)

ModuleUMAPPlot(sce, edge.alpha = 0.25, sample_edges = TRUE,
               edge_prop = 0.1, label_hubs = 0, keep_grey_edges = FALSE)
```



```{r}
hMEs <- GetMEs(sce, harmonized = TRUE)
mods <- setdiff(colnames(hMEs), "grey")

pals1 <- paletteer_c("ggthemes::Orange-Blue-White Diverging", 100) %>% rev()
celltype_colors <- c("#eaa052", "#B77DAF", "#b74147", "#90ad5b")

Clustered_DotPlot(
  seurat_object     = sce,
  features          = mods,
  group.by          = "celltype",
  colors_use_exp    = pals1,
  cluster_ident     = TRUE,
  cluster_feature   = TRUE,
  colors_use_idents = celltype_colors,
  legend_position   = "right",
  x_lab_rotate      = 45,
  raster            = FALSE
)
```

